site_name: HDU CGH toolkit [Quantum@HDU]
site_url: https://hducgh.researchi.group/docs/
use_directory_urls: true

repo_url: https://github.com/huchaoning/hducgh


theme:
  name: readthedocs
  language: en


edit_uri: edit/main/docs/


plugins:
  - search


nav:
  - Home: "index.md"
