site_name: Documentation of HDU CGH toolkit [Quantum@HDU]
site_url: https://hducgh.researchi.group/
use_directory_urls: true
copyright: "Quantum Metrology Laboratory, Hangzhou Dianzi University <a href='http://hduq.researchi.group'>[Quantum@HDU]</a>."

repo_url: https://github.com/huchaoning/hducgh


theme:
  name: readthedocs
  language: en


edit_uri: edit/main/docs/


plugins:
  - search

nav:
  - Home: "index.md"
  - Usage: "usage.md"


markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js

