site_name: HDU CGH toolkit [Quantum@HDU]
repo_url: https://github.com/huchaoning/cgh


theme:
  name: readthedocs
  language: en


edit_uri: edit/main/docs/


plugins:
  - search


nav:
  - Home: "index.md"
