name: build-wheel

on:
  workflow_dispatch:

jobs:
  ##################################
  ######## compile cpp/cnhu ########
  ##################################
  compile-cpp-cnhu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install tools
        run: pip install build

      - name: install just
        uses: taiki-e/install-action@just

      - name: build cpp
        run: |
          cd cpp/cnhu/cgh_engine
          just build

      - name: collect native library
        shell: bash
        run: |
          mkdir -p artifact

          if [ "$RUNNER_OS" = "Linux" ]; then
            cp src/hduq/cnhu/cgh/lib/*.so artifact/
          elif [ "$RUNNER_OS" = "Windows" ]; then
            cp src/hduq/cnhu/cgh/lib/*.dll artifact/
          elif [ "$RUNNER_OS" = "macOS" ]; then
            cp src/hduq/cnhu/cgh/lib/*.dylib artifact/
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: hduq-cnhu-cgh-cpp-${{ matrix.os }}
          path: artifact/


  ####################################
  ######## build python wheel ########
  ####################################
  build-wheel:
    runs-on: ubuntu-latest
    needs: compile-cpp-cnhu

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install build
        run: pip install build

      - name: download libs
        uses: actions/download-artifact@v4
        with:
          path: bundle/

      - name: assemble lib folder (cnhu)
        run: |
          mkdir -p src/hduq/cnhu/cgh/lib
          cp bundle/*/* src/hduq/cnhu/cgh/lib/
          touch src/hduq/cnhu/cgh/lib/__init__.py
          ls -l src/hduq/cnhu/cgh/lib/

      - name: build wheel
        run: python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: hduq-whl
          path: dist/*.whl
