name: build-and-publish

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "python/**"
      - "cpp/**"
      - ".github/workflows/**"

    tags:
      - 'v*'

jobs:
  #############################
  ######## compile cpp ########
  #############################
  compile-cpp:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install tools
        run: pip install build

      - name: install just
        uses: taiki-e/install-action@just

      - name: build cpp
        run: |
          just build-cpp

      - name: collect native library
        shell: bash
        run: |
          mkdir -p cpp-artifact

          if [ "$RUNNER_OS" = "Linux" ]; then
            cp python/src/spadecgh/assets/*.so cpp-artifact/
          elif [ "$RUNNER_OS" = "Windows" ]; then
            cp python/src/spadecgh/assets/*.dll cpp-artifact/
          elif [ "$RUNNER_OS" = "macOS" ]; then
            cp python/src/spadecgh/assets/*.dylib cpp-artifact/
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: cpp-artifact-${{ matrix.os }}
          path: cpp-artifact/


  ####################################
  ######## build python wheel ########
  ####################################
  build-wheel:
    runs-on: ubuntu-latest
    needs: compile-cpp

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3"

      - name: install build
        run: pip install build

      - name: download libs
        uses: actions/download-artifact@v4
        with:
          path: cpp-assets/

      - name: copy to assets folder
        run: |
          cp cpp-assets/*/* python/src/spadecgh/assets/
          ls -l python/src/spadecgh/assets/

      - name: build wheel
        run: cd python && python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: spadecgh-whl
          path: python/dist/*.whl


  #################################
  ######## publish to pypi ########
  #################################
  publish-pypi:
    runs-on: ubuntu-latest
    needs: build-wheel

    permissions:
      id-token: write

    steps:
      - name: download wheel
        uses: actions/download-artifact@v4
        with:
          name: spadecgh-whl
          path: dist/

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/