name: deploy-web-app

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "web_app/**"
      - "cpp/**"
      - ".github/workflows/**"

    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4

      - name: install just
        uses: taiki-e/install-action@just

      - name: setup emscripten
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 5.0.1
          emsdk-version: 5.0.5
          actions-cache-folder: 'emsdk-cache'

      - name: verify emscripten
        run: |
          emcc --version
          emcmake cmake --version

      - name: build wasm
        run: |
          mkdir -p cpp/build_wasm
          cd cpp/build_wasm 
          emcmake cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm ci
        run: just npm-ci
      
      - name: npm build
        run: just run-build

      - name: deploy web-app to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_app/dist
          destination_dir: web-app
          keep_files: true
          user_name: ${{ secrets.GH_PAGES_USER_NAME }}
          user_email: ${{ secrets.GH_PAGES_USER_EMAIL }}
